### ISSUE TITLE
Portfolio Feedback Week 4

### ISSUE THREAD

**Issue by alexandraiov** [w201rdada/portfolio-AlanyTan#1]
Gist: Create an AI to help users going through a traumatic event.

Kept: Most of the proposal.

Cut: I think the first paragraph under A data science approach to human relationship does not add a lot of value to the write-up.
>Agreed, re-wrote that part.

Rearranged: It is arranged well.

Added: I would like to know more about the interface. Is this an app? A website? Do subscribers have to pay for the service? Is it tiered ($10/month of basic help, $30 for paralegal help)?
>Thank you for bringing this topic up :-)  I added in the document, I want to offer free or near-free services so that more people can use the service.  

Comment: This is a very interesting concept and I would love to know more about it.

**Comment by AlanyTan** [comment]
Thank you.  It's great that you mentioned the price.  I actually wanted this service to be free, but forgot to even mention it :-)  so with your recommendation, I added that "free (or near free)" to the final version.
