### ISSUE TITLE
Subha's feedback on Alan's portfolio

### ISSUE THREAD

**Issue by subhap15** [w201rdada/portfolio-AlanyTan#2]
**Gist:** Use Data Science and AI to provide low cost but effective relationship therapy.

**Keep:** Everything except the reduction mentioned below regarding the 1st para content.

**Cut:** I feel content size in the 1st para under 'increasing relationship…'  can be reduced.

**Re-arrange:** Good flow of problem statement to solution, does not need rearrangement.

**Strengthen:** It will be good if you can address privacy concerns since this is sensitive information. 
> great recommendation.  I added privacy as one of the reasons for AI service in the final version.

Since this idea centers around the most unpredictable subject, humans, can you talk more about the dataset/source you will be using for risk prediction? As part of therapy sessions one of the most important area is, tracking progress from previous session to alter the course of sessions. It would be ideal to address follow-up process if the intent is to use 100% AI based therapists. 
>thanks for the recommendation. I added more details and previous studies on this subject to sustain the topic.

**Comment:** Use of Data Science as means to address relationship crisis is very unique and a first.  Great pick! Thanks for sharing.

**Comment by AlanyTan** [comment]
Thank you! very good recommendations, issues like privacy is a great addition to concerns in this kind of situations.
