### ISSUE TITLE
Chase Feedback : Relationship AI

### ISSUE THREAD

**Issue by csinguva** [w201rdada/portfolio-AlanyTan#3]
**Gist:**
 Use AI to provide improve personal relationships and reduce divorces

**Keep:**
 Everything except the paralegal AI.
>Yes, recommendation makes sense, removed paralegal in final version

**Cut:**
Paralegal AI and potentially upsell counseling AI/ Ecosystem for high-risk couples.  If you plan to offer divorce case management, you should do it as an alternative app. 
> agreed, Paralegal is really a separate service that can be used here, but not the core concept of this whole thing.  Thanks, I removed it in the final version. 

**Re-arrange:**
Good  - no changes

**Strengthen:** 
- Focus on risk prediction for couples aspect
--> How do you intend to measure the risk(questionnaire or behavioral tests?) and how do reduce emotional biases in risk measurement?
--> Does the questionnaire or risk measurement approach account for their existing health conditions(mood fluctuations, depression, menopause etc)
--> Define risk measurement approach and limitations 
--> How do you differentiate yourself from existing applications https://www.thedsmgroup.com/best-mobile-apps-for-couples/

- Content
--> Could you partner with other content creators and build ML to recommend the articles for the right demographic based on risk scoring. What is the rubric to build out the recommendation system if you plan to explore this route? 
>actually there are thoughts on this area - recommendation system for services that fit the needs of certain people.  The only reason I did not include it in this one is that I tried to focus on lowering cost - or free help for people in need.  But for a broader scope, recommendation system is considered.

- AI Paralegal:
--> I would diverge from this approach and potentially consider opening up the market for therapists & counsellers for high-risk couples. With the risk scoring, you could potentially create a matching market for right therapist/ counselor to a specific risk score. 
--> AI Paralegal would technically be at a point where the couple sees no future and would recommend doing it as a separate idea. 
> great recommendation.  I agree.  I took it off.

Comment: Great idea, but would need a lot of execution detail to make it successful. The market is begging for a solution like this- however, fine-tuning the product market strategy is key to success.
>Thanks!

**Comment by AlanyTan** [comment]
Very thoughtful feedback.  Recommendations are very good and explained in detail.  Thank you.
